name: Pull Request

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - initial-setup

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: docker-compose -f docker-compose.build.yml -f docker-compose.up.yml up --build
