name: Pull Request

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - initial-setup

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker-Compose
        uses: docker-compose up -d --build
      
      - name: Run Tests
        uses: npm test