name: Pull Request

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install --only=dev
        working-directory: ./app
      
      - name: Run linter
        run: npx eslint .
        working-directory: ./app

      - name: Run Tests
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build --exit-code-from node-app
